### ISSUE TITLE
Remove `prototyping` from broker names and SSB codebase

### ISSUE THREAD

**Issue by jskinne3** [GSA/notifications-api#1085]
This issue is a follow-on from #440 

When the org name changed from `gsa-tts-benefits-studio-prototyping` to `gsa-tts-benefits-studio` a mismatch arose with the Supplementary Service Broker (SSB) codebase, which contained hard-coded instances of the old name. These were propagated into our Cloud.gov configuration and our Terraform state file. We had to update references in all these locations in order to make the SSB function again, which was needed to [get the API sandbox working again](https://github.com/GSA/notifications-api/issues/883).

## What we did

1. We removed hard-coded instances of the old name: https://github.com/GSA/usnotify-ssb/pull/19
2. and disambiguated the name: https://github.com/GSA/usnotify-ssb/pull/22
3. then moved existing resources to the new name: https://github.com/GSA/usnotify-ssb/pull/24
4. ☠️ Because we ran some Terraform out of sequence during the above steps, we ended up with some resources existing _simultaneously_ under the old and new names. In order to complete the move of old resources, we had to explicitly remove new-named resources:

    <details><summary>from Terraform state, using <code>terraform state rm</code> and</summary>
    <pre>
    <code>

    $ docker-compose --env-file=.env.${ENV_NAME}.secrets run --rm terraform state rm 
    'module.broker_smtp.cloudfoundry_service_broker.space_scoped_broker["gsa-tts-benefits-studio/notify-demo"]' 
    Removed module.broker_smtp.cloudfoundry_service_broker.space_scoped_broker["gsa-tts-benefits-studio/notify-demo"]
    Successfully removed 1 resource instance(s).

    $ docker-compose --env-file=.env.${ENV_NAME}.secrets run --rm terraform state rm 
    'module.broker_smtp.cloudfoundry_service_broker.space_scoped_broker["gsa-tts-benefits-studio/notify-staging"]' 
    Removed module.broker_smtp.cloudfoundry_service_broker.space_scoped_broker["gsa-tts-benefits-studio/notify-staging"]
    Successfully removed 1 resource instance(s).

    $ docker-compose --env-file=.env.${ENV_NAME}.secrets run --rm terraform state rm 
    'module.broker_sms.cloudfoundry_service_broker.space_scoped_broker["gsa-tts-benefits-studio/notify-demo"]' 
    Removed module.broker_sms.cloudfoundry_service_broker.space_scoped_broker["gsa-tts-benefits-studio/notify-demo"]
    Successfully removed 1 resource instance(s).

    $ docker-compose --env-file=.env.${ENV_NAME}.secrets run --rm terraform state rm 
    'module.broker_sms.cloudfoundry_service_broker.space_scoped_broker["gsa-tts-benefits-studio/notify-staging"]' 
    Removed module.broker_sms.cloudfoundry_service_broker.space_scoped_broker["gsa-tts-benefits-studio/notify-staging"]
    Successfully removed 1 resource instance(s).
    
    </code>
    </pre>
    </details>
    <details><summary>from Cloud.gov, using <code>cf rename-service-broker</code></summary>
    <pre>
    <code>

    $ cf rename-service-broker ssb-sms-gsa-tts-benefits-studio-notify-demo remove-ssb-sms-gsa-tts-benefits-studio-notify-demo
    Renaming service broker ssb-sms-gsa-tts-benefits-studio-notify-demo to remove-ssb-sms-gsa-tts-benefits-studio-notify-demo as john.skinner@gsa.gov...
    OK

    $ cf rename-service-broker ssb-sms-gsa-tts-benefits-studio-notify-staging remove-ssb-sms-gsa-tts-benefits-studio-notify-staging
    Renaming service broker ssb-sms-gsa-tts-benefits-studio-notify-staging to remove-ssb-sms-gsa-tts-benefits-studio-notify-staging as john.skinner@gsa.gov...
    OK

    $ cf rename-service-broker ssb-smtp-gsa-tts-benefits-studio-notify-demo remove-ssb-smtp-gsa-tts-benefits-studio-notify-demo
    Renaming service broker ssb-smtp-gsa-tts-benefits-studio-notify-demo to remove-ssb-smtp-gsa-tts-benefits-studio-notify-demo as john.skinner@gsa.gov...
    OK

    $ cf rename-service-broker ssb-smtp-gsa-tts-benefits-studio-notify-staging remove-ssb-smtp-gsa-tts-benefits-studio-notify-staging
    Renaming service broker ssb-smtp-gsa-tts-benefits-studio-notify-staging to remove-ssb-smtp-gsa-tts-benefits-studio-notify-staging as john.skinner@gsa.gov...
    OK

    </code>
    </pre>
    </details>
5. We then applied the renames by passing a trivial PR through all the CI/CD: https://github.com/GSA/usnotify-ssb/pull/26

As of 14 June 2024 I see no more broker names nor Terraform identifiers with `-prototyping` in them. So this issue is mainly done. But some cleanup remains:

## Still to-dos
- [x] Double-check this outstanding version upgrade: https://github.com/GSA/usnotify-ssb/pull/21
- [x] Add to SSB README [Troubleshooting](https://github.com/GSA/usnotify-ssb?tab=readme-ov-file#troubleshooting) section
- [x] Remove these unused, renamed service brokers:
  ```lang-text
  remove-ssb-sms-gsa-tts-benefits-studio-notify-demo
  remove-ssb-sms-gsa-tts-benefits-studio-notify-staging
  remove-ssb-smtp-gsa-tts-benefits-studio-notify-staging
  remove-ssb-smtp-gsa-tts-benefits-studio-notify-demo
  ```
- [x] Optionally, remove [now-completed move blocks](https://github.com/GSA/usnotify-ssb/blob/main/broker/moves.tf) from SSB. 

## 🏆 Bonus stuff we did
* We updated some documentation and software versions throughout the above process, including the [minimum version of Terraform](https://github.com/GSA/usnotify-ssb/pull/23) in SSB
* We discovered missing DNS records:
    `    ssb.notify.gov` :no_entry_sign: was not routing correctly to the subdomain
    `dev.ssb.notify.gov` which is [required by the SSB](https://github.com/GSA/usnotify-ssb/blob/9e9ca64d8491e6a7baf86d2db68f1d8d118f8ee6/terraform.development.tfvars#L9)
   * We created NS and DS records in the .ssb.notify.gov zone, and
   * documented the problem: https://github.com/GSA-TTS/datagov-brokerpak-smtp/pull/37
   
## Thanks
This was a big project; these people helped me a lot:
* @ccostino 
* @rahearn 
* @eric-gade
* @mogul

**Comment by jskinne3** [comment]
Update on one of the to-dos: [A PR for the SSB Troubleshooting section](https://github.com/GSA/usnotify-ssb/pull/27/files)

**Comment by jskinne3** [comment]
READMEs improved with these PRs:
- https://github.com/GSA/usnotify-ssb/pull/27/
- https://github.com/GSA-TTS/datagov-brokerpak-smtp/pull/37/
- https://github.com/GSA/notifications-api/pull/1045/
I am checking the box for README improvements

**Comment by jskinne3** [comment]
@ccostino, @stvnrlly, or @ecayer I propose that this issue is ready to close

https://github.com/GSA/usnotify-ssb/pull/30 was the last PR in this issue and it is optional, really

**Comment by ccostino** [comment]
Awesome, thank you @jskinne3!  The final PR is merged so we're closing this as done.
