### ISSUE TITLE
Clean up remaining Terraform modules/resources with deprecated attributes

### ISSUE THREAD

**Issue by ccostino** [GSA/notifications-api#1139]
There are still a couple of lingering modules and/or resources in our Terraform files that have deprecated attributes set.  We need to remove these to make sure we're staying ahead of Terraform module updates that will eventually remove these attributes/features.

It appears to be just references to `recursive_delete` in this case, and one is specifically showing up in our Admin app Terraform output:

```
│ Warning: Argument is deprecated
│ 
│   with module.logo_upload_bucket.cloudfoundry_service_instance.bucket,
│   on .terraform/modules/logo_upload_bucket/s3/main.tf line 14, in resource "cloudfoundry_service_instance" "bucket":
│   14:   recursive_delete = var.recursive_delete
│ 
│ Since CF API v3, recursive delete is always done on the cloudcontroller
│ side. This will be removed in future releases
```

Note that this is referencing something not in our own Terraform files it seems, but a module we're relying on.

We've gotten the fixes/changes in place needed to address this for the other warnings we previously had, so let's clean the rest of them out.  A quick search through the code base shows the following files still contain references to this attribute:

### API Terraform files

* terraform/development/main.tf:4:  recursive_delete = true
* terraform/development/main.tf:13:  recursive_delete = local.recursive_delete
* terraform/production/main.tf:93:#   recursive_delete = local.recursive_delete

### Admin Terraform files

* terraform/demo/main.tf:6:  recursive_delete = false
* terraform/demo/main.tf:28:  recursive_delete = local.recursive_delete
* terraform/development/main.tf:4:  recursive_delete = true
* terraform/development/main.tf:18:  recursive_delete = local.recursive_delete
* terraform/production/main.tf:6:  recursive_delete = false
* terraform/production/main.tf:28:  recursive_delete = local.recursive_delete
* terraform/production/main.tf:63:  recursive_delete = local.recursive_delete
* terraform/sandbox/main.tf:6:  recursive_delete = true
* terraform/sandbox/main.tf:15:  recursive_delete = local.recursive_delete
* terraform/sandbox/main.tf:38:  recursive_delete = local.recursive_delete
* terraform/staging/main.tf:6:  recursive_delete = true
* terraform/staging/main.tf:36:  recursive_delete = local.recursive_delete

## Implementation Sketch and Acceptance Criteria

- [x] Find all remaining references to the `recursive_delete` attribute across the API and Admin repos and see what can be done about removing them.
- [x] Test the updates in sandbox and staging first, to make sure `terraform plan` shows success and the `terraform apply` step succeeds as well
- [x] Make the remaining changes in the `demo` and `production` environments

## Security Considerations

- We want to make sure our infrastructure is being managed properly and kept up-to-date to stay in sync with the tooling we're using, especially in the case of security updates.

**Comment by jskinne3** [comment]
As of PR https://github.com/GSA/notifications-admin/pull/1781 I believe this issue is complete. I propose to @ecayer and @ccostino that we close it.

**Comment by ccostino** [comment]
Confirming that this appears to be the case for me too.  Thank you for all of the work on this, @jskinne3! 🎉
