### ISSUE TITLE
Enhance download-csv-file-by-name command

### ISSUE THREAD

**Issue by terrazoon** [GSA/notifications-api#1165]
Right now the download-csv-file-by-name command prints to the log.  Not only does this mean that you have to search the log, but also the csv file is logged one line at a time and the log is not default sorted by time.   So it is a headache to search for the output.  In addition, because we are using a print statement we are skipping some sanitization steps the logger does for us.

It would be better if people invoking the command were able to receive the csv file in an email. We only want platform_admins to run this command so maybe in addition to the -f flag that specifies what file to download, we could add a -e flag that provides the user's email address.

The command would have to check if the owner of the email address actually is a platform admin, but that should be simple enough.

**Comment by ecayer** [comment]
Note: this ended with just downloading the csv file, not e-mailing!
