### ISSUE TITLE
Investigate our current logging configuration with Flask

### ISSUE THREAD

**Issue by terrazoon** [GSA/notifications-api#1268]
Investigate our current logging configuration with Flask and look over the [Flask Handling Application Errors Guide](https://flask.palletsprojects.com/en/3.0.x/errorhandling/) to see if there is anything else we could be doing with the newer version of Flask that we're now running

**Comment by terrazoon** [comment]
It seems like the Notify UK people have broadly implemented the best practices suggested in the document above.  The only other thing to consider is the the use of Sentry, but that is a paid subscription and means that our errors would flow to a third party sight.  This opens up money and security questions, and we are already using New Relic for this purpose (although maybe Sentry is cheaper?  It looks like it's $80 a month for unlimited use although I didn't look too deeply into it).  So nothing to do on this one.

**Comment by ccostino** [comment]
Right, that's an additional paid service and requires other setup as well with the app, whereas with New Relic it's literally just install the agent and make sure it can talk to the service.

Thanks for taking a closer look at this, @terrazoon!
