### ISSUE TITLE
Ensure that users don't need to add `+1` country code to US numbers on signup

### ISSUE THREAD

**Issue by rahearn** [GSA/notifications-api#135]

**Comment by rahearn** [comment]
Current status as of 12/5 is that it appears that some numbers work fine without +1, and some numbers require it

**Comment by stvnrlly** [comment]
Is it the number itself that makes a difference, or the way it was entered at account creation? If it's the latter, we could change the validation in that form to require 10-digit phone numbers without the country code.

**Comment by rahearn** [comment]
Inspect use and function of `notification_utils.recipients.validate_and_format_phone_number` as part of this

**Comment by stvnrlly** [comment]
Dropping a note about other 11-digit phone numbers that start with `+1`: https://en.wikipedia.org/wiki/List_of_country_calling_codes. I'd hope that `phonenumbers` is able to handle that, but we'll need to check.
