### ISSUE TITLE
Find out why REDIS uses so much memory!

### ISSUE THREAD

**Issue by terrazoon** [GSA/notifications-api#1459]
Running notifications for US Census, we survived the first run of 25k notifications, but during the second run on the same day, our workers started crashing and we could not recover from the crash.  We determined that this is because REDIS ran out of memory.  It was configured for 3 large nodes.  We changed that to 5 large nodes and are hoping that is sufficient.

However, the way cloud foundry works, 5 large nodes is the most we can have, so if we are storing useless stuff that ought to be purged, we need to know that and figure out what is going on.  Analyze REDIS for API and see what is being stored in it and when that data is being cleaned up.

NOTE: The problem is these keys: retry-tasks and database-tasks.  Search code on QueueNames.DATABASE_TASKS and QueueNames.RETRY.  Figure out how to add one week expiration times to the data going into these 'queues' (i.e., redis).

**Comment by ccostino** [comment]
Some additional details we've learned:  [the Elasticache plans offered by cloud.gov](https://www.cloud.gov/docs/services/aws-elasticache/#plans) seem to indicate that you only have a total of 1.3 GB of memory available to you for the entire cluster (for the large plans), regardless of size their size.  Based on our investigation and research into the issue we saw in production last night, this seems to track as the max memory reported back was 1.03 GB and the total used memory was also 1.03 GB.

We ended up purging all of the data in the `retry-tasks` key and that freed up enough memory to get things going again, and presumably this will take some time to fill back up as we've not had to do this before.  That said, we absolutely need to make sure the data going into our Redis instance(s) (we should check the admin, too!) is set to expire properly so it doesn't persist forever.

The switch to the `5node-large` plan is more a preemptive move at this point to be able to maintain responsiveness during periods of intense activity; the memory cap is the actual limitation though, and we have an open question with cloud.gov to see why that is and if our understanding is correct.

**Comment by ccostino** [comment]
cloud.gov let us know that we can adjust the memory management policy, but it'd have to be a support request to them and would result in a brief period of downtime.  At the moment our cluster is using the default `volatile-lru` memory management policy (see the [AWS guides for more info](https://docs.aws.amazon.com/AmazonElastiCache/latest/dg/ParameterGroups.Management.html), but we can change that and it'd be no additional cost.

They also shared [this doc on key eviction in Redis](https://redis.io/docs/latest/develop/reference/eviction/), which helps explain more of what happens in these situations and what to be on watch for, and [this doc from AWS about the OOM - out of memory - error](https://repost.aws/knowledge-center/oom-command-not-allowed-redis) and what to do.
