### ISSUE TITLE
Investigate user account email re-validation

### ISSUE THREAD

**Issue by rahearn** [GSA/notifications-api#151]
More context in: https://gsa-tts.slack.com/archives/C0107UC0W1M/p1671639985818379

**Comment by tdlowden** [comment]
I haven't seen this happen again... maybe a short term glitch?

**Comment by rahearn** [comment]
![Image](https://user-images.githubusercontent.com/285842/218190053-1575e016-22c1-4ceb-92d8-cfd65413ad1f.png)

**Comment by rahearn** [comment]
This screen is triggered every 90 days. This has been documented within IA-2
