### ISSUE TITLE
Pull delivery receipts from Cloudwatch into the application

### ISSUE THREAD

**Issue by rahearn** [GSA/notifications-api#152]
If so, we need to support them. If not, we need to reimagine how things like research-mode works

Delivery receipts code path starts in `notifications_sms_callback.py` and `process_sms_client_response_tasks.py`

- [ ] SMS metrics are accurate during sending
- [ ] SMS metrics are retained over time
- [ ] Documentation of what the metrics mean
- [ ] Documentation of how the metrics work, technically

**Comment by rahearn** [comment]
Notes from 10x team on delivery receipts https://docs.google.com/document/d/1RtzwCodVe6C0DiBnBy7cTQaC_lMRyaGbz21k8mlJPRE/edit?disco=AAAAhzLI21U

Likely need to both support and also update how research-mode works.

**Comment by tdlowden** [comment]
@rahearn will get access to that doc to @terrazoon and @A-Shumway42.

@terrazoon noticed that the files mentioned are not up to date. May require a discussion in engineering meeting after @stvnrlly returns to re-scope and add context

**Comment by rahearn** [comment]
Whoever picks this up, get in touch with me and I'll get your AWS account setup, and we can talk more in depth about where any AWS changes required would need to be documented in the brokerpaks

**Comment by terrazoon** [comment]
https://github.com/GSA/notifications-api/pull/256

This PR is for the python changes.  I'll make a separate PR for the terraform changes.

**Comment by terrazoon** [comment]
Terraform:  https://github.com/GSA/ttsnotify-brokerpak-sms/pull/4
