### ISSUE TITLE
Add code coverage tests for API

### ISSUE THREAD

**Issue by stvnrlly** [GSA/notifications-api#230]
As an initial thought, https://coverage.readthedocs.io/en/7.2.3/ might be a good starting point.

To complete:
- [x] Select a code coverage tool
- [x] See if the default setup works
- [x] Check configuration options for useful stuff
- [x] Add tool to `make test`
- [x] Add tool to GitHub Actions

**Comment by tdlowden** [comment]
hey @A-Shumway42, i *think* i saw a PR for this? If so, can you update this card with info and the PR link when ready, then move this card to `in review`?

**Comment by A-Shumway42** [comment]
Will do. I'll get right on that!
