### ISSUE TITLE
Onboard Andrew S to Notify

### ISSUE THREAD

**Issue by stvnrlly** [GSA/notifications-api#231]
- [x] Join [the GSA GitHub org](https://github.com/GSA/GitHub-Administration#join-the-gsa-organization)
- [x] Get permissions for the repos
- [x] Get access to the cloud.gov org && spaces
- [ ] Get [access to AWS](https://handbook.tts.gsa.gov/launching-software/infrastructure/#cloud-service-provider-csp-sandbox-accounts), if necessary
- [ ] Get [access to New Relic](https://handbook.tts.gsa.gov/tools/new-relic/#how-do-i-get-access-to-new-relic), if necessary
- [x] Create the local `.env` file by copying `sample.env` and running `./run.sh` within the `terraform/development` folder
- [ ] Do stuff!

**Comment by tdlowden** [comment]
@A-Shumway42 have we completed all the above? Is this card ok to close, or are there outstanding things left?

**Comment by A-Shumway42** [comment]
I believe that is complete.
