### ISSUE TITLE
Store data only for unsuccessful messages

### ISSUE THREAD

**Issue by stvnrlly** [GSA/notifications-api#233]
Currently, the application stores phone number and variable data for texts sent, allowing senders to see specifically what was sent, what succeeded, and what failed. We've shortened the retention period to ~1 day (from 7 days), but would prefer to avoid storing that PII in the first place as much as possible.

This data is stored in Postgres, with the message addressee and variables stored in `notifications` and aggregate data stored in `notification_history`. As part of the nightly jobs, it's `insert_notification_history_delete_notifications` that moves records from one to the other.

To complete:
- [ ] Message data is not stored in the database until after the first delivery attempt
- [ ] If the delivery attempt succeeds, data goes directly to `notification_history`
- [ ] If the delivery fails, data goes into `notifications` with the relevant status info
- [ ] If delivery succeeds on retry, data is moved to `notification_history` and deleted from `notifications`
- [ ] Retention period is extended back to 7 days

**Comment by tdlowden** [comment]
Is this dependent on #152?

**Comment by tdlowden** [comment]
Interested to hear how this would play out for the user after complete. Would there be nothing for them to download post-send other than failed messages?

I ask because there has been talk about how to update case-management systems with the information that a message has been sent to them. We have been saying that a user would need to download the post-send report and re-ingest it into their systems.

Given the above, the only output a user could download would be a log of failed messages, correct?

**Comment by terrazoon** [comment]
I tried to implement this by not writing notifications to the database until they failed.  I got it partially working but there were a lot of unit test failures and I became concerned about a couple things:   1) There seems to be a notion of a "saved-sms" which can be when the sms is in research mode or possibly for other reasons.  If we aren't writing them to the db except on failure, then there is no way to save them.  That was a cause of a number of the unit test failures.   2) It's just a generally invasive change that breaks many things.

So I thought about and decided to try another way -- go ahead and write to the db, but immediately after a successful send, delete from the notifications table and write to the notification_history table instead.    I think (?) this accomplishes the same objectives.  I've tested my PR and it works.  It was only a few lines changed and two broken unit tests, easily fixed.

**Comment by tdlowden** [comment]
Thanks, @terrazoon. Can you link the PR here and move this card into the "in review" column. @stvnrlly can review it when he returns.

**Comment by terrazoon** [comment]
https://github.com/GSA/notifications-api/pull/238

**Comment by stvnrlly** [comment]
> I think (?) this accomplishes the same objectives.

Yeah, this should serve our immediate purposes well!

In the future, I'd still like to find a way to skip the brief save, too, as I think there's a lot of value in being able to say that we never save that information to the database. But we have enough stuff to do now that it's not worth forcing the heavy lift.
