### ISSUE TITLE
Remove statsd

### ISSUE THREAD

**Issue by stvnrlly** [GSA/notifications-api#243]
The existing codebase uses `statsd` for tracking internal metrics. We won't be using that. To complete:

- [x] Document what is being logged to `statsd`
- [x] Check effort level to remove the service
- [x] If not tightly coupled, remove the service

We'll use the documentation to tackle functionality replacement in a separate issue, if necessary.

**Comment by terrazoon** [comment]
https://github.com/GSA/notifications-api/pull/244

https://github.com/GSA/notifications-utils/pull/32

**Comment by terrazoon** [comment]
Here is how statsd was being used prior to removal:


delivery/send_to_providers.py
sms.total-time  (looks like the time from when notification was created until when it was sent)
sms.test-key.total-time (same as sms.total-time)
sms.live-key.total-time (same as sms.total-time)
sms.live-key.high-volume.total-time (same as sms.total_time, depends on service.high_volume)
sms.live-key.not-high-volume.total-time (same as sms.total_time, depends on service.high_volume)

celery/process_ses_receipts_tasks.py
callback.ses.{} (status)
callback.ses.elapsed-time (now minus sent-at time)

celery/nightly_tasks.py
timeout-sending.{notification.sent_by} (increments a count of timeouts)

clients/sms/aws_sns.py
clients.sns.error (increments an error count)
clients.sns.request-time
clients.sns.success (increments a success count)

clients/email/aws_ses.py (same as aws_sns.py)
clients.ses.error
clients.ses.request-time
clients.ses.success

clients/email/aws_ses_stub.py -- similar to aws_ses.py
