### ISSUE TITLE
Send boilerplate auto-reply for inbound SMS

### ISSUE THREAD

**Issue by stvnrlly** [GSA/notifications-api#248]
The starting point for this is likely in `/app/notifications/receive_notifications.py`. There is some existing support for inbound SMS, but it is primarily focused on displaying message content for the service users and not on real-time response.

The MVP is likely:
- [ ] Test that inbound messages make it through to the application
- [ ] Add a template with stock language, to be provided by @em-herrick 
- [ ] When a message is received, kick off the message sending flow as if it were sent by the service associated with the phone number using that template
- [ ] If no service is associated, or multiple services, use the default service

**Comment by tdlowden** [comment]
per @rahearn, this can be done via AWS directly and is not worth exploring in application at this stage.

**Comment by tdlowden** [comment]
Current understanding is that this method would provide the user the ability to customize the message in-app, but it also would be considered two-way messaging and is not in scope for LATO period. This is a full-ATO feature.

**Comment by stvnrlly** [comment]
Closing this in favor of #271. If we decide to revive this idea in the future, the implementation might be entirely different.
