### ISSUE TITLE
Document what AWS SNS does when sending an international SMS

### ISSUE THREAD

**Issue by stvnrlly** [GSA/notifications-api#259]
Chart here seems to indicate there are varying levels of support to send internationally within SNS: https://docs.aws.amazon.com/sns/latest/dg/sns-supported-regions-countries.html

To complete:
- [ ] Find any AWS documentation about pricing differences in sending internationally
- [ ] Try to send an international text?
- [ ] Document the details in the application

Also looks like we need to register a Sender ID?

**Comment by tdlowden** [comment]
Closing as not planned as we are currently limiting to +1 country code
