### ISSUE TITLE
Only use UTC times

### ISSUE THREAD

**Issue by stvnrlly** [GSA/notifications-api#260]
Currently, the application converts back and forth to Eastern Time in a few places, using utilities provided by `notifications-utils`. This adds complexity and possible confusion since we'll actually be working over multiple time zones. 

Once we're UTC-only, we can more confidently show users their local time over in the UI.

**Comment by terrazoon** [comment]
https://github.com/GSA/notifications-api/pull/272

**Comment by terrazoon** [comment]
If we are going to implement this, I think we should pass the name of the user's timezone and the current timezone offset in every request.   Then the backend can do its utc->local and local->utc conversions using that.
