### ISSUE TITLE
Set up autoresponders in AWS console

### ISSUE THREAD

**Issue by stvnrlly** [GSA/notifications-api#271]
To complete:

- [x] Draft text for default auto-reply
- [x] Test with trial accounts
- [ ] Add an auto-reply for each active phone number

**Comment by tdlowden** [comment]
From Taylor at AWS: While not built-in this functionality can be accomplished by using a lambda to respond to incoming messages. It would look similar to [this tutorial](https://aws.amazon.com/blogs/messaging-and-targeting/create-an-sms-chatbox-with-amazon-pinpoint-and-lex/), but with the chat bot cut out.  Let me know if you have any other questions.

**Comment by stvnrlly** [comment]
Turns out that this _is_ feasible after all. The `HELP` auto-response in Pinpoint appears to be used for other incoming messages, as well.
