### ISSUE TITLE
Switch all services to FIPS-endpoint

### ISSUE THREAD

**Issue by rahearn** [GSA/notifications-api#274]
s3 buckets should have fips endpoints in the credentials.

other services may need to use these endpoints: https://aws.amazon.com/compliance/fips/

**Comment by stvnrlly** [comment]
There's a `boto` config to use the FIPS endpoints: `use_fips_endpoint` in https://botocore.amazonaws.com/v1/documentation/api/latest/reference/config.html. 

After completing this, let's check to see if we can update our LATO documentation.

**Comment by ccostino** [comment]
Noting here that we'll also have to update our [allowlist ACL](https://github.com/GSA/notifications-api/blob/main/deploy-config/egress_proxy/notify-api-staging.allow.acl) with the FIPS-enabled endpoints as well across all environments.

**Comment by ccostino** [comment]
🤦 not as simple as adding the config keyword directly; you do need to instantiate a `botocore.config.Config` object and pass it in through that.
