### ISSUE TITLE
Get our emails out of spam

### ISSUE THREAD

**Issue by stvnrlly** [GSA/notifications-api#308]
Our DNS records appear to be correct, and AWS believes our sender reputation is healthy. Nevertheless, our emails are going to spam. Given that we're only sending a few emails, let's try this:

- Have a few people explicitly report the emails as _not_ spam
- See if that fixes things

**Comment by tdlowden** [comment]
@stvnrlly should we close this, given you noted it appears they are correct after all?

**Comment by stvnrlly** [comment]
Renamed and updated this to be about the underlying issue, since it still exists.

**Comment by tdlowden** [comment]
@stvnrlly do all our emails come from the same place, despite the environment we're operating in?
