### ISSUE TITLE
Set up opt-out list for each phone number in AWS console

### ISSUE THREAD

**Issue by terrazoon** [GSA/notifications-api#312]
Changing this issue over as new AWS features make this much simpler. We should set up an opt-out list in Pinpoint for each phone number. This will give them independent opt-out lists rather than a combined account-level one.

Eventually we can use [Pinpoint API calls](https://docs.aws.amazon.com/pinpoint/latest/apireference_smsvoicev2/API_CreateOptOutList.html) to do this automatically, but for now it is few enough numbers to just set it up in the console manually.

---

ORIGINAL ISSUE TEXT:

I previously discussed this with Ryan Ahearn.   Right now it is quite likely that opting out of one service will result unexpectedly in being opted out of all services.

This is a long term problem and it will be some time before it occurs, but we need to keep track of the association between phones and the services they subscribe to.   Obviously we don't want to store any PII so one solution might be as follows:

Make a table with two columns "service_id" and "hash".    Every time someone subscribes, a hash of their phone number is added to this table, associating it with the correct service.

Then, before sending, we grab the opt-out phone numbers from AWS and check them against this table, using the service_id of whoever wants to send the message.  If we decide that the user has opted out of the service, we reject the message with some useful error message and update the 'provider_response' appropriately in the notifications table.

There might be other ways to do it, but that is what came to mind.

**Comment by terrazoon** [comment]
Now that I think about, this may not be necessary.  It's confusing at the moment because we only have one sender phone number.

1.  If I set up service A and service B, and I opt out of service B, I'm really opting out of the shared phone number, so I won't be able to receive messages from service A (this has been verified to happen).

2. But, if in the long run every service is going to have its own sender phone number, there should be no confusion.  

3. If, instead, every organization has its own sender phone number, then opting out of one service will opt you out of all services -- which may not be desirable, but we may actually not have control over that, since opt out is handled by the carrier.


I'm thinking the correct approach is to adjust the granularity of the sender phone numbers.

**Comment by terrazoon** [comment]
Uh-oh.

https://stackoverflow.com/questions/76483827/amazon-aws-opt-in-via-text-start-sms-response

**Comment by terrazoon** [comment]
It looks like SNS may not support communicate with the carriers regarding opt-in.  I texted 'unstop' and ATT says I should be receiving messages, but SNS still has me on the opt out list.

Another thing to try would be:

1. Text STOP on phone
2. Manually clear the phone number from the opt-out list in the AWS Console
3. Send a message and see if it goes through

Expected:  No, it doesn't go through because the carrier blocks it

4. Text UNSTOP
5.  Send another message

Expected: Message will go through

If the message does go through, then maybe we just need to clear the opt-out list every five minutes and let the carriers handle opt-out and opt-in.   From a design standpoint, there's no reason for our app to be involved in managing that (unless there are carrier limitations of some kind etc)

**Comment by stvnrlly** [comment]
Updated the top comment to reflect the new Pinpoint feature we can use to do this.

**Comment by xlorepdarkhelm** [comment]
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/pinpoint-sms-voice-v2.html

**Comment by xlorepdarkhelm** [comment]
I did some restructuring to how we're handling clients and implementing them, to help facilitate setting up the client for pinpoint. Working on the pinpoint client now, so then I can build out the process for making opt-out lists.
