### ISSUE TITLE
Fix the PII scrubbing of successful messages for csv reports

### ISSUE THREAD

**Issue by tdlowden** [GSA/notifications-api#317]
The downloadable reports after send currently display the phone number of the message recipient. Expected action is that successful messages have number scrubbed to `1`.

**Comment by terrazoon** [comment]
According to the error message, it looks like there is a permissions issue on staging where staging does not want to allow the aws_cloudwatch_client to call out and retry logs from cloudwatch.

**Comment by terrazoon** [comment]
One option may be to replace cloudwatch with SNS topic subscriptions (assuming we have permissions for those).

**Comment by terrazoon** [comment]
Fixed by:  https://github.com/GSA/notifications-api/pull/335

The egress proxy was preventing us from being able to read from cloudwatch.  The fix was to add cloudwatch to the allowed acl.
