### ISSUE TITLE
Unable to create new send message templates due to process_type being None

### ISSUE THREAD

**Issue by ccostino** [GSA/notifications-api#326]
When you create a new template (either brand new or copying from an existing one), the admin app errors out upon saving the initial changes due to `process_type` being `None` instead of `normal` or `priority`.  We recently removed the priority queue support so this should just default to `normal`, however it looks like we may have missed a spot where this happens.

## Expected Behavior

- Create or copy a new template to send messages from
- Save the initial changes to create the template
- Go to the next step in the process of prepping a message to send

## Actual Behavior

- Create or copy a new template to send messages from
- Save the initial changes to create the template
- See an error screen because of a 500 response in the admin app and a 400 response in the API

## Additional Information

Here is the error I saw in the API logs:  `notify-admin "{"status_code": 400, "errors": [{"error": "ValidationError", "message": "process_type None is not one of [normal, priority]"}]}" [in /Users/carloacostino/Projects/notifications-api/app/errors.py:66]`

This is the error from the admin app logs:  `notifications_python_client.errors.HTTPError: 400 - [{'error': 'ValidationError', 'message': 'process_type None is not one of [normal, priority]'}]`

And the corresponding screen in the admin app when this happens:

<img width="1022" alt="Screen Shot 2023-07-03 at 11 53 02 AM" src="https://github.com/GSA/notifications-api/assets/121565/c032d0b3-eee2-4f1c-a417-5683d34c1cbb">

## Security Considerations

- None

**Comment by ccostino** [comment]
Note that we did have the form set to automatically submit the `process_type` as `normal` with [the recent priority queue changes](https://github.com/GSA/notifications-admin/pull/561)!

**Comment by terrazoon** [comment]
This should be fixed by this PR:  https://github.com/GSA/notifications-admin/pull/594
