### ISSUE TITLE
Create properties on org model to process agreement info, adjust Agreement model with new details

### ISSUE THREAD

**Issue by stvnrlly** [GSA/notifications-api#331]
The second step of implementing [ADR 0005](https://github.com/GSA/notifications-api/blob/main/docs/adrs/0005-agreement-data-model.md)

This is a collection of properties on the existing org model to pull in the data from the linked agreements.

- `is_active` should return whether the org has (1) an agreement with "signed" status and (2) we are within the period of performance
- `agreement` which just returns that active agreement or None
- `has_mou` should return whether the active agreement is an MOU (which would limit the org's services to the free tier only)
- `remaining_budget` calculates, well, the remaining budget based on sent messages and the cost of those messages. Note that there's trickiness here with the interaction with the free tier
- `remaining_messages` converts the remaining budget to remaining message fragments, based on our message rate

It's possible that those last two will require a bunch more thinking. If so, let's ship the first 3 and move the others to a new issue.

To complete:
- [x] Add those properties
- [x] Add tests for those properties

**Comment by xlorepdarkhelm** [comment]
I adjusted the `models.py` class `Agreement` to use two new Enum classes, `AgreementType` and `AgreementStatus`, which have options as specified in ADR-0005.

I also added the migration upgrade/downgrade for this.

**Comment by xlorepdarkhelm** [comment]
For less confusion, `is_active` is changed to be `agreement_active`
