### ISSUE TITLE
Messages are hanging in `pending` forever

### ISSUE THREAD

**Issue by tdlowden** [GSA/notifications-api#360]
I sent messages and their delivery status is not updating, even after an hour:

![Image](https://github.com/GSA/notifications-api/assets/6556888/a418bae6-31e5-43c2-8800-0e138c1e29cf)

**Comment by tdlowden** [comment]
Update: @stvnrlly noted this is prob a result of things getting blocked by the ergress proxy. I was working in `demo` env, and ports need to be opened to allow the logs to be accessed by the application.

**Comment by tdlowden** [comment]
@stvnrlly do we think this was resolved?

**Comment by tdlowden** [comment]
I do not think this is resolved as per a test just now. Message was received, but after 5 minutes, still reflects "pending/sending"

**Comment by terrazoon** [comment]
I think we've identified the problem -- the log groups have their names structured a little differently depending on what tier they are on.  So the code seems to work for staging and local and nowhere else.  However, I do not have permission to run describe_log_groups with boto3, and when I log into the various console they don't have any resources.  I may be looking in the wrong place, waiting for guidance.
