### ISSUE TITLE
Create tech one-pager for common partner questions

### ISSUE THREAD

**Issue by stvnrlly** [GSA/notifications-api#377]
This includes:
- [ ] product description
- [ ] Data encryption
- [ ] Basic infrastructure including network
- [ ] No integration with your system needed
- [ ] Records management
- [ ] Integration availability (e.g. none)
- [ ] How the platform is accessed (e.g. single-sign on/via the web)

**Comment by em-herrick** [comment]
I have drafted an outline as a jumping off point. This is becoming timely as we've had two partners execute MOU's and we'd like to get local security review's jump started.  We also have seen many IT departments give a blanket "no" with the wrong/no information in hand, so there is a need to clear up with Notify is and is not from a technical perspective.

This could also live on Github (and maybe pieces do) but I've started a [google doc](https://docs.google.com/document/d/1Samq-O1ExlHnU-8_E2AgO7jJZLnRvAx7Z766jsQjdy8/edit) as a jumping off point.
