### ISSUE TITLE
Set up SNS for Studio use via brokerpak

### ISSUE THREAD

**Issue by stvnrlly** [GSA/notifications-api#38]
Tasks:

- [x] deploy sms brokerpak apps
- [x] move AWS commercial prod / us-west-2 out of sandbox
- [x] register AWS commercial prod / us-west-2 phone number
- [x] wait for sandbox support request to be done
- [x] update staging app terraform to provision sns service (#177)
~- [ ] share staging instance with sandbox space~ instance sharing not available with space-scoped brokers
- [x] move AWS commercial prod / us-east-2 out of sandbox
- [x] configure sandbox to use us-east-2
- [x] move AWS commercial prod / us-east-1 out of sandbox
- [x] register AWS commercial prod / us-east-1 phone number
- [x] wait for demo sandbox support request to be done
- [x] update demo app terraform to provision sns service
- [x] wait for staging & demo phone number registrations to be complete
- [x] update app code to use SNS services
- [x] move AWS govcloud prod / us-gov-west-1 out of sandbox
- [x] register AWS govcloud prod / us-gov-west-1 phone number
- [x] wait for prod support requests to be done
- [x] wait for prod phone number registrations to be complete
- [x] update prod app terraform to provision sns service
- [x] register AWS commercial prod / us-east-2 phone number for sandbox
- [x] update sandbox deploy-config with that number

**Comment by rahearn** [comment]
Setting aside until we have our own accounts
