### ISSUE TITLE
Update team permissions to be consistent across developers

### ISSUE THREAD

**Issue by stvnrlly** [GSA/notifications-api#381]
With our team becoming more established, we need to make sure all of our engineers have access to the things they need to be able to help support, troubleshoot, and develop for the system.  This means going through our [onboarding guide](https://github.com/GSA/notifications-api/blob/main/docs/infra-overview.md#onboarding) and making sure folks are set up with the correct accounts and permissions.

As a baseline, @stvnrlly & @ccostino's accounts can serve as a model for other team members.

## Implementation Sketch and Acceptance Criteria

- [x] Create a means of tracking account access and status for all team members for compliance and audit purposes
- [x] Adjust cloud.gov accounts and permissions for all team members
- [x] Adjust GitHub accounts and permissions for all team members
- [x] Adjust AWS accounts and permissions for all team members
- [ ] Adjust New Relic accounts and permissions for all team members

## Security Considerations

- We need to make sure our team members have the access they require to do their jobs effectively, but the rule of least privilege necessary applies.
- We need to keep track of who has access to what for compliance and traceability reasons; periodic audits of this information should be conducted.
- As folks onboard and offboard, we need to make sure we update account access accordingly.

**Comment by ccostino** [comment]
I've taken a look at cloud.gov and all permissions appear correct to me.  Once I start walking through things with folks we'll make any adjustments if we need to.

**Comment by ccostino** [comment]
I think we're good to call this done now!  I spent time with folks yesterday and created AWS accounts as needed and updated the tracker (which has been shared internally) to reflect the recent changes.

Anything else at this point should be a new issue to track additional work/changes!
