### ISSUE TITLE
Examine the senders of emails from each environment and adjust if necessary

### ISSUE THREAD

**Issue by stvnrlly** [GSA/notifications-api#382]
Make sure that emails are coming from `whoever@notify.gov` for the production environment, in particular

**Comment by terrazoon** [comment]
Is this story related to this ticket?  https://github.com/orgs/GSA/projects/20/views/1?pane=issue&itemId=22594079

Is the ask to replace testsender@<goofyfakeaddress> with something like admin@notify.gov?
