### ISSUE TITLE
Update & unpin `gunicorn`

### ISSUE THREAD

**Issue by stvnrlly** [GSA/notifications-api#389]
To complete:

- [x] Review the reason that `gunicorn` was pinned
- [x] Confirm that it can be safely updated
- [x] Update & unpin

**Comment by terrazoon** [comment]
It was pinned because of this issue which has only recently been fixed (July):

     fix thread worker: fix socket removal from the queue at checkout 21.x

I upgrade to the latest 21.2.0 and am seeing no problems.

**Comment by ccostino** [comment]
Nice!  🤞 that's all it was!
