### ISSUE TITLE
Use `moto` to mock text sending in local development

### ISSUE THREAD

**Issue by stvnrlly** [GSA/notifications-api#390]
We'd like a setup where local dev can simulate the AWS infrastructure, but without needing (1) extra infra costs or (2) sending test texts to real hardware. It can make things fiddly. The `moto` library is currently used for tests and initially seems like it fits the need. 

Let's start by trying to mock the text sending. I think we still want to keep the option to really send a text, as some dev work will rely on the interaction between the application and AWS.

**Comment by terrazoon** [comment]
I'm running into some issues.  My initial thinking was to create a command like 'send-test-notification' which could be run from the command line as `pipenv run flask command send-test-notification` with various flags.  However:

1. The concepts of Moto and mock only some to work in pytest-land
2. Commands do not work in pytest land, which is to say flask is not going to recognize something in test code even if it is flagged as a command.
3. We already have a KEY_TYPE_TEST that does most of what we want.

So right now I'm able to do `pipenv run flask command send-test-notification` and specify the key type as test and I can see it go all the way through the work flow with no problems.   However, it's not going to increment counts properly, so I think I need to use KEY_TYPE_NORMAL for that, which gets us back to needing actual mocks.  Hmmm!

**Comment by terrazoon** [comment]
I think I will leave it as a command and add a new key type, dev, that will bypass the sns calls.
