### ISSUE TITLE
Allow custom port values in egress proxy

### ISSUE THREAD

**Issue by stvnrlly** [GSA/notifications-api#393]
This recently changed upstream. We either need to:

- Find a way to inject our own environment variables at deploy
- Fork the project and set our own value

Apparently, forking is expected. However, it'd be nice if we can find a way to continue sharing a codebase that's otherwise working perfectly for us.

**Comment by VRagulina** [comment]
Could be assigned to 18F engineer

**Comment by ccostino** [comment]
@stvnrlly, @jskinne3 and I will catch up with you about this soon to get more clarity on the issue and what we ought to be doing here. :-)

**Comment by stvnrlly** [comment]
This has been resolved on the egress proxy side! With the `no_proxy` setting, internal routings can avoid the proxy all together, which makes sense as they're never leaving cloud.gov.
