### ISSUE TITLE
Bug with worker failure

### ISSUE THREAD

**Issue by terrazoon** [GSA/notifications-api#427]

**Comment by terrazoon** [comment]
I noticed that when I run `make run-profile` and watch the output, there are now two worker errors.

The first error involves the task tend-providers-back-to-middle which should have been removed as part of PR #404 (increase code coverage), but was not.

**Comment by terrazoon** [comment]
The second error seems to be introduced in PR #415 ([Update Flask plugins and related dependencies](https://github.com/GSA/notifications-api/commit/114aa45f19433bd4a565071426b8eff395047228)).  Investigating.

**Comment by terrazoon** [comment]
The check_job_status task in scheduled_tasks looks like it is failing due to the SQLAlchemy upgrade.  Will look further tomorrow.

**Comment by ccostino** [comment]
Oh, the Flask-SQLAlchemy update?  SQLAlchemy itself is still on the 1.4.x series, the 2.0.x version hasn't been pulled in yet.  Flask-SQLAlchemy, however, [that was a fairly large update](https://github.com/pallets-eco/flask-sqlalchemy/compare/2.5.1...3.0.5)...
