### ISSUE TITLE
Re-examine quotas to make sure they align with what we want for pilots

### ISSUE THREAD

**Issue by tdlowden** [GSA/notifications-api#443]
Is the 5000 global daily quota what we actually want? Feels like it could/should be higher.

@stvnrlly, now that we (i think) have no service daily quota, do you have an idea of what the max daily quota should be?

**Comment by tdlowden** [comment]
We are unsure if the 5000 global quota is 5000 message send attempts vs 5000 rows written to db (which would be only on failures). 

We need to 1. figure out exactly what's happening, 2. communicate that better in the UI (and maybe code, too?) and 3. decide the number we actually want to enforce, based on (1)

**Comment by stvnrlly** [comment]
The only short-term limit is the retention limit, and https://github.com/GSA/notifications-api/issues/457 should go a long way towards handling it.
