### ISSUE TITLE
Get necessary people `platform admin` perms on `prod`

### ISSUE THREAD

**Issue by tdlowden** [GSA/notifications-api#486]
I am thinking pretty much this whole product team + Partner leads should be platform admins in `prod`. Does anyone have any objections?

That would be Steven, Carlo, Ken, Andrew, Jonathan, Meghan, Tim, Em right now.

**Comment by tdlowden** [comment]
We should add Cathy and Cliff to this list, as well

**Comment by stvnrlly** [comment]
This is waiting for #553
