### ISSUE TITLE
Confirm that we get accurate sent/failed/delivered metrics

### ISSUE THREAD

**Issue by stvnrlly** [GSA/notifications-api#49]
Notify has some built-in stats for messages. We'll want them reliably working as part of an MVP.

To close, we should have:

- [ ] SMS metrics are accurate during sending
- [ ] SMS metrics are retained over time
- [ ] Documentation of what the metrics mean
- [ ] Documentation of how the metrics work, technically

**Comment by tdlowden** [comment]
Closed in favor of #152
