### ISSUE TITLE
Document AWS infrastructure configuration

### ISSUE THREAD

**Issue by stvnrlly** [GSA/notifications-api#50]

**Comment by rahearn** [comment]
Documenting within https://docs.google.com/document/d/1QtgTBVAnT4Dt2IFsniKwDJPaIu_xcb38ii7iCPEKQtQ/edit#heading=h.h4zc9q25e5oc

**Comment by rahearn** [comment]
@stvnrlly I think the AWS config is sufficiently documented within ☝, pending updates from moving into terraform. Can you please review and ask any outstanding questions you have?

**Comment by rahearn** [comment]
> That might just be links to existing TTS documentation.

added a link to the handbook page on the AWS sandbox
