### ISSUE TITLE
Try out shorter log-checking times

### ISSUE THREAD

**Issue by stvnrlly** [GSA/notifications-api#512]
It seems safe to bump things up from 5 minutes. Logs start populating within 30 seconds, so we could try that, or give a little extra buffer with 60 seconds.

To complete:
- [ ] Shorten times used in `aws_cloudwatch.py`
- [ ] Check retry logic to make sure it still makes sense in terms of timing

**Comment by terrazoon** [comment]
The reason this ticket is still open is that if we try to check delivery receipts more frequently (adjusting the schedule from every 5 minutes to every minute for example) we start getting celery worker failures, which means that a certain fraction of messages will never get updated from Pending.   In local testing, checking every 5 minutes gives a 100% success rate and checking every minute only 80%.

**Comment by ccostino** [comment]
Thanks for the heads up on the Celery workers, @terrazoon!

Before we declare victory with what we have, let's investigate why the Celery workers start to fail if we adjust to 1 minute checks.  Ideally we want to start checking after one minute, but waiting five minutes after that initial check is fine.
