### ISSUE TITLE
Add an ALIAS record for Notify.gov apex

### ISSUE THREAD

**Issue by stvnrlly** [GSA/notifications-api#515]
See https://github.com/18F/dns/blob/main/doc/architecture.md#terraform for some details about how TTS is implementing this. There are also a variety of implementation examples in that repo.

We need to determine the correct values to use for our own setup, as nothing we have set up now seems to align with other implementations. In particular, all of those use Cloudfront with a pointer to cloud.gov's zone ID, which implies that we should be able to get the same info somewhere.

We also might need to set up a new instance of the cloud.gov external domain service, using https://cloud.gov/docs/services/external-domain-service/#how-to-create-an-instance-of-this-service.  If we do, we should set this up with the CDN this time.

Additionally, we'll want to get the `www.notify.gov` DNS records in place too; they'll also redirect to `beta.notify.gov` for the time being, but once we are out of the pilot we can adjust them to point to the apex (`notify.gov`).

**Comment by ccostino** [comment]
This is now live and the redirect is working!  Thank you @stvnrlly for all the help with this! 🎉
