### ISSUE TITLE
Document known API endpoints

### ISSUE THREAD

**Issue by stvnrlly** [GSA/notifications-api#53]
The UK service has [API documentation available](https://docs.notifications.service.gov.uk/rest-api.html). Still, 10x has learned more through their explorations. 

To close, we should:

- [ ] Document what we've done to learn about the API
- [ ] Document what we learned beyond the UK docs

**Comment by rahearn** [comment]
This should maybe be worked alongside #27

**Comment by stvnrlly** [comment]
For some of the 10x learning, see https://docs.google.com/document/d/1S5c-LxuQLhAtZQKKsECmsllVGmBe34Z195sbRVEzUgw/edit#heading=h.134fqdup8d3m
