### ISSUE TITLE
Onboard Anastasia Gradova

### ISSUE THREAD

**Issue by ccostino** [GSA/notifications-api#607]
@anagradova is a new team member joining the Notify.gov Product Team!

@ccostino will be the onboarding buddy with @stvnrlly as backup.  To help with onboarding, we've prepared a few materials:

- [Onboarding checklist for Anastasia](https://docs.google.com/document/d/1PLbJYL75k6LBp3ruQrDIoxoF1QcBHHYGo5lY3HlicCo/edit)
- [Onboarding guide for Anastasia](https://docs.google.com/document/d/1s0l9O6BDQo19h8Fym0ZYffph8WlYE_yVOYvcg4VlMU0/edit)

@ccostino will set up time with @anagradova to review onboarding materials and help work through the checklist and initial project set up.

## Acceptance Criteria

- [x] Work through onboarding checklist and take care of account setup, access to tools, and permissions needed
- [x] Answer any questions and review studio materials
- [x] Introduce @anagradova to the team

## Security Considerations

- Review security compliance policies with @anagradova and answer any questions.
- Ensure MFA is set up where required.

**Comment by ccostino** [comment]
@anagradova and I have finished going through account access and permissions!

**Comment by tdlowden** [comment]
hey @ccostino and @anagradova, anything outstanding? can we close this issue?

**Comment by ccostino** [comment]
I believe we can, @tdlowden!

@anagradova, if you have any other questions or anything please let us know and ask. 🙁  Thanks!
