### ISSUE TITLE
Annual message count is not incrementing with messages sent

### ISSUE THREAD

**Issue by tdlowden** [GSA/notifications-api#644]
As evidenced in both live service dashboard and usage sections, the annual message quota is not increasing with sent messages. The service that these screenshots are from has sent over 2000 messages this year at time of screenshots. The count by month is accurate, but the annual count is not.

![Image](https://github.com/GSA/notifications-api/assets/6556888/412d51d1-27b5-475d-a9ce-22ca96949f8c)

![Image](https://github.com/GSA/notifications-api/assets/6556888/9153dfb2-ce9e-4bf7-a21b-39589bf3c4e1)

**Comment by tdlowden** [comment]
I went into the platform admin settings and manually increased the free message allowance to 250K. After that, everything populated, BUT... the service I upgraded the free message count for has NOT sent 4600 messages. They have sent a little over 2000, which makes me think that this count is actually application wide. I'll open a new ticket for that.

**Comment by ccostino** [comment]
@em-herrick and @stvnrlly, this is what we were discussing about the limits still being off in sprint planning this week, at least in the cases of 40K messages - it seems like we may have a quicker fix than messing with more calculations?  Especially when one of these last PRs goes in for the SMS allowance (https://github.com/GSA/notifications-admin/pull/1195).
