### ISSUE TITLE
The `failed message quota` is counting message send attempts rather than failures

### ISSUE THREAD

**Issue by tdlowden** [GSA/notifications-api#648]
My understanding was that with smart retention, the 10K cap was for rows written to the db, which would be specifically `failed` messages. What I can see currently from the UI is that messages sent appear to be counted, instead. This screenshot is from the main dashboard of a live service. (Note: Despite the dashboard saying this is supposed to be `daily`, I have verified it is the global remaining count. A different issue addresses displaying actual daily limit).

![Image](https://github.com/GSA/notifications-api/assets/6556888/b927f9ec-6454-43ee-bbe3-3e97f2b410ad)

**Comment by terrazoon** [comment]
Some issues came up with making this change that are greater than the scope of the change.  Namely, do we want to have PII in the db and enforce a 10000 row limit due to PII at all?  Putting this back to up next pending outcome of the meeting.
