### ISSUE TITLE
Replace single-column option tables with Enum

### ISSUE THREAD

**Issue by stvnrlly** [GSA/notifications-api#682]
Tables to tackle:
- [x] `auth_type`
- [x] `branding_type`
- [x] `invite_status_type`
- [x] `job_status`
- [x] `key_types`
- [x] `notification_status_types`
- [x] `organization_types` (all orgs can get the same limit)
- [x] `service_callback_type`

We are assuming based on #79 that this is a good choice for all of these. If during implementation that is disproven, we should change course rather than forcing this through.

**Comment by ccostino** [comment]
Closing this as done!
