### ISSUE TITLE
The UI and reports are not reflecting any data about sends to opted out numbers

### ISSUE THREAD

**Issue by tdlowden** [GSA/notifications-api#683]
@ccostino was testing the opt-out/opt-in functionality after setting keywords in AWS (which worked!).  BUT,  despite being able to verify the message send failed in the logs (and had a response that mentioned they opted out), we could not establish that from the UI nor the downloadable report. To out knowledge, the message went from `pending` to the abyss, and is not reflected in `failed` or `delivered`. 

![Image](https://github.com/GSA/notifications-api/assets/6556888/7acb3f4b-3b86-4557-9da0-32eca8525e73)

See https://gsa-tts.slack.com/archives/C0107UC0W1M/p1702657829930119?thread_ts=1702657355.822169&cid=C0107UC0W1M for more

**Comment by tdlowden** [comment]
From Steven to replicate:

- in notify, send yourself a text (to confirm a working state)
- reply "STOP" to notify number
- in notify, send one-off message to that phone
- check what happens in the dashboard
- if the failure doesn't show up, check the logs for error messages, and continue from there
- if the failure does show up, just give the response-handling code a review to check for places a message might have fallen out a side door or something?
- reply "UNSTOP" to notify number to get yourself opted back in

**Comment by xlorepdarkhelm** [comment]
So, the message shows up, but not as a failure. It is showing as a success, from what I can tell.

**Comment by tdlowden** [comment]
Can you put screenshots here to demonstrate? What are the next steps to remedy, in your opinion?

**Comment by xlorepdarkhelm** [comment]
I am including the logs from a successful, not opted out text.

[success_message_logs.txt](https://github.com/GSA/notifications-api/files/13789597/success_message_logs.txt)

**Comment by xlorepdarkhelm** [comment]
I am including the logs from an errored out, unsuccessful, opted out text.

[error_message_logs.txt](https://github.com/GSA/notifications-api/files/13789609/error_message_logs.txt)

**Comment by xlorepdarkhelm** [comment]
There is a definite error, I've tracked it in the logs, investigating further.

**Comment by xlorepdarkhelm** [comment]
I will be tracking down what is expected to be returned from the function that is failing, and am considering that maybe returning "OPT-OUT" or something in the place of where that is attempted to be returned, will then in turn make this work.

**Comment by xlorepdarkhelm** [comment]
Ok, so I changed it so that it says "Unknown Carrier" to be more universal in case something else causes the same error. I have verified locally that opted out messages are tracked as failures now.

**Comment by tdlowden** [comment]
Fascinating. It was related to something with the carrier field vs the actual failure? Can you explain more?

**Comment by xlorepdarkhelm** [comment]
It had to do with the aws_cloudwatch.py `check_sms` method, when writing out a failure, it was looking up the `"phoneCarrier"` field from the `message["delivery"]` structure, and that didn't exist. So it was sending out a `KeyError` and crashing, not actually writing out the failure.
