### ISSUE TITLE
Clean up after new SMS provider change

### ISSUE THREAD

**Issue by jimmoffet** [GSA/notifications-api#7]
- [x] Create env var for origin email address for default service provider and modify migrations accordingly
- [x] Create env var for origin SMS phone number for default service provider and modify migrations accordingly
- [x] Remove all references firetext and mmg SMS providers and clients
- [x] Ascertain whether need to keep/remove/modify the `supports_international` flag for notifications providers

**Comment by rahearn** [comment]
Areas to update still:

- [ ] research_mode_tasks.py
- [ ] notifications_sms_callback.py
- [ ] process_sms_client_response_tasks.py
- [ ] receive_notification.py
- [ ] provider_details_dao.py
- [ ] send_to_providers.py
