### ISSUE TITLE
API:  Investigate our use of the orderedset library and remove it if possible, otherwise replace and update it

### ISSUE THREAD

**Issue by ccostino** [GSA/notifications-api#765]
The API project pulls in the [`orderedset`](https://pypi.org/project/orderedset/) library but doesn't seem to actually use it at all.

This library hasn't been updated in some time and specifically mentions only working with Python versions 2.7 - 3.8.  It appears to work with Python 3.9 as well, but we know it does not work with 3.11+, which will prevent us from upgrading Python in the future.

The API only seems to list the library as a dependency but doesn't actually use it.  Our preference would be to remove it entirely if we don't need it.  If we do need it, then we'll have to research some alternatives; [a list of ordered set packages can be found on PyPI](https://pypi.org/search/?q=orderedset).

## Why is this an external library?

Because an `OrderedSet` doesn't exist in the standard library as of yet.  See [this discussion on the Python Ideas list](https://discuss.python.org/t/add-orderedset-to-stdlib/12730) for more details.

## Implementation Sketch and Acceptance Criteria

- [ ] Verify whether or not we're using `orderedset` at all in the API; if we're not using it at all, remove it.
- [ ] If we are using it for something, then we need to find a suitable replacement
   - [ ] Verify that the Admin project itself needs this, or if it's actually just a [notification-utils dependency](https://github.com/GSA/notifications-utils/issues/103) that can be managed solely through that module.
   - [ ] Research some alternative packages ([a list can be found on PyPI](https://pypi.org/search/?q=orderedset) to start with), paying close attention to the following:
      - Does it do what we need it to do?
      - Does it work with recent versions of Python?
      - Does it require a different set of paradigms, or is it a drop in replacement for the use of `set` in Python?
      - Is it well maintained and has it been updated recently?
      - Is the author known, and/or is there a support community?
   - [ ] Make the swap in packages within the `pyproject.toml` file, update the `poetry.lock` file, and update the code and tests as necessary.

## Security Considerations

- We'll need to make sure the project is well-maintained and also adheres to security best practices.
- Removing or updating this library will enable to us to keep our own apps well-maintained and update other dependencies or Python itself as needed.

**Comment by terrazoon** [comment]
I think OrderedSet is used by notifications-utils so api and admin get stuck with it that way.

At first glance Ordered-set-37 or StableSet look like possible replacements

**Comment by ccostino** [comment]
D'oh, good point, @terrazoon!  I forgot to look in the utils side of things, I'll double check over there.  Thanks for the reminder, and thanks for the initial suggestions!

We're not quite ready to tackle this work yet, but I wanted to get the issues written up so they're ready to go for the future. 🙂

**Comment by terrazoon** [comment]
I've found the best replacement to orderedset is ordered_set.

API does not use orderedset directly, only via notifications-utils.  I have tested api locally using my branch of notifications-utils where orderedset was replaced by ordered_set, and everything looks ok.

**Comment by ccostino** [comment]
This work has been completed!
