### ISSUE TITLE
Investigate Verify Infrastructure Check failure - drift detected for egress space

### ISSUE THREAD

**Issue by stvnrlly** [GSA/notifications-api#789]
From the Actions:

```
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # module.egress-space.cloudfoundry_space.public_egress will be updated in-place
  ~ resource "cloudfoundry_space" "public_egress" {
      + delete_recursive_allowed = true
        id                       = "63506464-c7e2-4743-a7b3-4a8d45f14fb9"
        name                     = "notify-production-egress"
        # (7 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Warning: Argument is deprecated

  with module.ses_email.cloudfoundry_service_instance.ses,
  on ../shared/ses/main.tf line 22, in resource "cloudfoundry_service_instance" "ses":
  22:   recursive_delete = var.recursive_delete

Since CF API v3, recursive delete is always done on the cloudcontroller side.
This will be removed in future releases

(and 4 more similar warnings elsewhere)
Changes detected!
```

To get started on this, we need to answer a few questions:
- Is this all related to `recursive_delete = var.recursive_delete`. It _looks_ like it is.
- What is "the cloudcontroller side"? Do we control that?
- If so, what's the change to make?
- If not, what other action should we take?

To complete this, we should also document the purpose of `deployers` in `main.tf` files.

**Comment by xlorepdarkhelm** [comment]
We need to account for that `recursive_delete = false` for production.

Both production & demo still need to have the recursive_delete variable removed.

**Comment by xlorepdarkhelm** [comment]
Also the cloudfoundry provider version to 0.53.1 for them.

**Comment by ccostino** [comment]
We think we're set with this, at least from a local dev and staging perspective, but it looks like the infrastructure updates didn't actually run with the last staging deploy and I'm not sure why.  We want to get those fully working first because we should at least see the staging infrastructure drift check work after that's complete.

Once we get this ironed out, we can wrap up with production and demo!

**Comment by ccostino** [comment]
Staging appears to be working just fine now with the changes, so we need to get the rest in place for `production` and `demo` now, especially as this will hold up future deployments until everything matches.

**Comment by ccostino** [comment]
https://github.com/GSA/notifications-api/pull/851 takes care of fixing the rest of the things!

**Comment by ccostino** [comment]
We've fixed the rest of this and are going to close this issue as it _should_ be working!  If we continue to see failures we'll open a new issue.

**Comment by ccostino** [comment]
We're re-opening this issue to finish the remaining work on it!  It seems staging is okay again, but production and demo are still failing their checks for the API.

**Comment by ccostino** [comment]
This has been sorted out with the work that @jskinne3 has recently done and we've gotten ahead of almost all of it!  I'll open a separate issue for one or two remaining stragglers on the deprecated attributes.
