### ISSUE TITLE
Review New Relic logs and create bug report issues

### ISSUE THREAD

**Issue by stvnrlly** [GSA/notifications-api#872]
There are some recurring errors in our applications that don't appear to be causing active problems. We want to catch those and resolve them before that changes.

To complete:
- [x] Review API error stats in New Relic
- [x] Review admin error stats in New Relic
- [x] Create new GitHub issues, including stack traces and other information, for new bugs

**Comment by ccostino** [comment]
I've finished going through the admin app errors and will be working on the API soon!

**Comment by ccostino** [comment]
Issues have been created and are now being tracked by epics as well.
