### ISSUE TITLE
update-template command needs to clear template keys

### ISSUE THREAD

**Issue by terrazoon** [GSA/notifications-api#884]
We ran into an issue while trying to change the organization invite template.  The "update-templates" command updates the template in the database correctly, but the old version of the template lingers in redis and never gets purged (no expiration date).  So the behavior is as if the template never changed.

The update-templates commands should clear all templated-related redis keys.  It should NOT do a flush all, as there are now a number of keys flying around related to logging in and responding to invites, etc, and doing a flush all is potentially disruptive, at least on production.

**Comment by ccostino** [comment]
Yes, specifically [`clear-cache`](https://github.com/GSA/notifications-admin/blob/main/app/main/views/platform_admin.py#L569-L634), which needs to also be updated to include the `organization` template keys along with the existing `service` template keys already accounted for.

**Comment by ccostino** [comment]
Taken care of with https://github.com/GSA/notifications-api/pull/886!
