### ISSUE TITLE
Update DNS records with group email for DMARC/SPIF DNS logs

### ISSUE THREAD

**Issue by stvnrlly** [GSA/notifications-api#89]

**Comment by tdlowden** [comment]
@rahearn is this related to the work we've recently been talking about, or is it separate?

**Comment by rahearn** [comment]
@stvnrlly this is covering just all of the various DNS records we'll need to create on the eventual domain(s) we send email from, right?

**Comment by stvnrlly** [comment]
Sorry, I don't remember and am having trouble parsing the title. I think I just converted this from a draft issue rather than creating it myself, so I'm inclined to agree with your interpretation.

**Comment by stvnrlly** [comment]
Closing since DNS records are now established
