### ISSUE TITLE
Sanitize SQL inputs against injection in migrations

### ISSUE THREAD

**Issue by stvnrlly** [GSA/notifications-api#91]

**Comment by terrazoon** [comment]
Do we have reason to think that any SQL injection vulnerabilities currently exist in the migrations?

I've gone through and looked at the first 25 migrations and don't see any.   There are some patterns that might be questionable, such as in 0025_notify_service_data with its use of format(), but in that migration all the values provided to format() are hardcoded, so there is no actual vulnerability.

It would be nice if there were some static scanner that looked for sql injection patterns, but it seems like the only automated tools are dynamic scanners.

**Comment by terrazoon** [comment]
More examples where the pattern is questionable but there is no actual vulnerability as written:

0028_fix_reg_template_history

**Comment by terrazoon** [comment]
The migrations with ** above contain ad-hoc queries that are built up with f-strings.  Probably they should be fixed.
