### ISSUE TITLE
Implement max age for SNS notifications

### ISSUE THREAD

**Issue by stvnrlly** [GSA/notifications-api#92]

**Comment by tdlowden** [comment]
@stvnrlly should we bump this into the backlog? I am unsure of the need.

**Comment by terrazoon** [comment]
@stvnrlly , @ccostino ... anything to do for this one?

**Comment by terrazoon** [comment]
My understanding is that AWS would call this TTL, and that AWS doesn't current support TTL for SMS.  They do support it for a number of other formats I'm not familiar with (FCM, Baidu).
I would say de facto we have a max age of 4 hours, so we comply with the spirit of the best practice at least, but there is no work to be done here.

Also, TTL seems closely tied to a dead letter queue, which we aren't using.  We try hard to deliver for 4 hours, and if we can't we just call it a fail and move on.  Which seems like good behavior. I'm not sure what purpose a dead letter queue would serve other than as a post-mortem, and now we can use the logs for that anyway (failure message will be in the logs).

**Comment by terrazoon** [comment]
After discussion with @stvnrlly, closing.
