### ISSUE TITLE
Final checks and tests of the Flask upgrade PRs

### ISSUE THREAD

**Issue by ccostino** [GSA/notifications-api#953]
We have two open PRs for the Flask upgrades that have been worked on that are ready for full review and testing.  We want to make sure everything is still functioning properly and no new errors are happening with all of the dependency upgrades.

We also want to get these PRs merged as they're a requirement to the SQLAlchemy upgrade PR that is also open.

## Implementation Sketch and Acceptance Criteria

- [x] Pull down the branches in each of the PRs for the API and Admin to your local machine:
   - API:  https://github.com/GSA/notifications-api/pull/901
   - Admin:  https://github.com/GSA/notifications-admin/pull/1387
- [x] Run `make bootstrap` in both repos on your machine to make sure you get all of the dependency updates; there will be quite a few!
- [x] Run the API and Admin locally and work through the [QA test template](https://github.com/GSA/notifications-admin/blob/main/.github/ISSUE_TEMPLATE/manual_qa_template.yml) on the site to test all of the site features and functionality to make sure everything works and no new errors are showing up; if any do, document them in this ticket.

## Security Considerations

- Being able to update to the newest version of Flask lets us take advantage of new features and incorporate security enhancements and fixes.
- This update lets us update a number of other dependencies as well.

**Comment by anagradova** [comment]
I updated the local code with make bootstrap for notifications-admin and notifications-api, completed the manual QA template, and clicked through every link. No errors were found.

**Comment by ccostino** [comment]
The Flask updates have been merged and deployed to staging!
