### ISSUE TITLE
Investigate why /v2 URLs are being called (mostly in the API, but some Admin as well)

### ISSUE THREAD

**Issue by ccostino** [GSA/notifications-api#955]
To our knowledge, none of the workflows or API calls we are making in the app should be going to the `/v2` routes, yet there appear to be a handful of them in the logs still and they're clearly being used.

A glance in the staging and production logs over the last month searching for `"/v2"` in the [cloud.gov logs](https://logs.fr.cloud.gov/) shows the following `v2` routes showing up with a variety of different requests:

* /api/v2/
* /v2/
* /v2/notifications/
* /v2/template/
* /v2/templates

The first two items are likely just random routes being hit either from things probing for open endpoints or scanners testing for things, but the last 3 appear to be tied to app functionality as they appear a lot in the logs.

## Implementation Sketch and Acceptance Criteria

- [x] Review the [cloud.gov logs](https://logs.fr.cloud.gov/) by searching for `"/v2" and make a note of the endpoints you see, any requests arguments supplied with them, what the response from the app was, etc.
- [x] Trace the endpoints back through the code of the apps (most will be in API, but some are in Admin) and make note of the following:
   - Are these real/valid endpoints?
   - What view(s) are they tied to?
   - What is the logic associated with the route?
- [x] For each endpoint, try and figure out what is triggering the calls to the routes in the first place, if they're not just random scans/probes for open endpoints.
   - Generally speaking, if these are legitimate, they are likely coming from an API client (there are multiple!) in the Admin and you'll need to trace things back and forth, but there could be other sources or direct calls as well
   - The response code from the app may also yield insight into what type of call it was (e.g., a 2XX response vs. a 401, 403, 404, 5XX, etc.)
- [x] Document all findings here and/or create a Google Doc with more details to link to

## Security Considerations

- We want to make sure we understand why these endpoints are being requested and if they're legitimate requests or not.
- In the case of legitimate requests, we need to know why they're using the `/v2` URLs.

**Comment by terrazoon** [comment]
I have only started to look at the logs, but the v2 calls seem to fall in two exclusive categories -- the completely bogus, and the unauthorized.   Looks like scanners.

"GET /api/v2/swagger/?configUrl=https://xss.smarpo.com/test.json HTTP/1.1" 404

"GET /v2/template/uuid HTTP/1.1" 401

**Comment by ccostino** [comment]
Yup, after further discussion and review, this is what we're dealing with.  These will be taken care of via PR https://github.com/GSA/notifications-api/pull/1037, so closing this issue out!
