### ISSUE TITLE
Final tests for SQLAlchemy 2.0.x upgrade

### ISSUE THREAD

**Issue by ccostino** [GSA/notifications-api#960]
With the Flask upgrades complete and merged, we can turn our attention to our final tests for the SQLAlchemy upgrade to get this merged as well.  The previous work was completed in https://github.com/GSA/notifications-api/issues/825, now we want to ensure that the site still functions properly given the updates that have taken place.

The PR with this work is here: https://github.com/GSA/notifications-api/pull/946

**NOTE:** Once you switch to the branch, you'll need to run `make bootstrap` to make sure all of your dependencies get updated to match the PR.

## Implementation Sketch and Acceptance Criteria

- [x] Review the changes to the [open PR](https://github.com/GSA/notifications-api/pull/946) to ensure that the modifications are in line with what's expected with the switch from the 1.4.x series to the 2.0.x series
   - You can refer to both [Aditi's migration guide](https://docs.google.com/document/d/1bXH9FEWVDICZC2mrEgNVXVrMQepANC5jLM07CPcaWho/edit#heading=h.qgdhphcht9jx) and the [SQLAlchemy 2.0.x migration guide](https://docs.sqlalchemy.org/en/20/changelog/migration_20.html) itself
   - There are `black` formatting changes as a part of this PR, so please be mindful of those as well!
- [ ] Test the site and the API manually to make sure everything still functions as expected
   - Use the [manual QA checklist](https://github.com/GSA/notifications-admin/blob/main/.github/ISSUE_TEMPLATE/manual_qa_template.yml) for help in determining what to test
   - Pay particular attention to any action on the site that communicates with the database and be sure to test that it is still functioning as expected and no errors or other unexpected messages are showing up in the API logs
- [ ] Document any findings in a code review on the PR and/or follow-up in other reviews as needed

## Security Considerations

- Getting this upgrade in is a huge win for us as it puts us on the current major release version of SQLAlchemy and ensures we stay up-to-date with any future updates and security patches.
- This also dovetails with taking advantage of improvements with newer versions Flask and Python itself; the newer version of SQLAlchemy is tested against or with these newer versions, where as the 1.4.x series is not.

**Comment by xlorepdarkhelm** [comment]
name: "QA Checklist"
description: "Use this template to manually QA for prod push"
title: "QA for prod push: Admin #[insert PR number], API #[insert PR number], Utils #[insert PR number]"

body:
- type: checkboxes
  id: Logging_in
  attributes:
    label: Log In
    options:
      - label: local resolves/renders
      - label: Clicking sign in takes you to login.gov page
      - label: Finishing login.gov steps sends you back to Notify local correctly & logged in.
      - label: Choosing a service brings you to the dashboard for that service, if on the choose service page.

- type: checkboxes
  id: send_template
  attributes:
    label: Create a template and send
    options:
      - label: Clicking “Send messages” brings you to templates page
      - label: When “Create a template” button is clicked, the option to create new or copy existing template appears
      - label: Uploading a csv is quick and automatically directs you to the preview/send page
      - label: Formatting looks clean and in place
      - label: Message dashboard populates and shows “pending” until call is made to AWS for delivery receipt


- type: checkboxes
  id: send__copied_template
  attributes:
    label: Send a message from copied template
    options:
      - label: When “Create a template” button is clicked, the option to create new or copy existing template appears
      - label: Clicking “copy an existing template” allows you to choose from pre-existing template
      - label: After editing, the new template saves and you prepare to send


- type: checkboxes
  id: send__existing_template
  attributes:
    label: Send a message from existing template
    options:
      - label: Clicking on existing template brings you to preview screen with `prepare to send` button
      - label: All else above persists as true (formatting, send, dashboard, etc)

- type: checkboxes
  id: download_report
  attributes:
    label: Download the csv delivery report
    options:
      - label: Clicking on the csv download directly after a message send downloads a report that contains the data we expect
      - label: The batch report appears on the main dashboard batch table with accurate information
      - label: Clicking on the csv download link from the main dashboard downloads a report that contains the data we expect

- type: checkboxes
  id: invite_member
  attributes:
    label: Invite a team member
    options:
      - label: Clicking on “Team” in settings  brings you to team member screen
      - label: Clicking “Invite a team member” brings you to email and permissions screen
      - label: Clicking invite team member sends an invite and shows confirmation
      - label: Invite email provides live link that works to register new team member

- type: checkboxes
  id: delete_member
  attributes:
    label: Delete a team member
    options:
      - label: From team member screen, clicking “Change Details” on a specific profile brings you to that person’s profile
      - label: Clicking on “Remove this team member” prompts a confirmation
      - label: Clicking the confirmation removes the team member
    
- type: checkboxes
  id: sign_out
  attributes:
    label: Sign Out
    options:
      - label: Hitting “Sign Out” takes you back to the homepage and logs you out

**Comment by xlorepdarkhelm** [comment]
Otherwise, everything looks good. All tests run, all came back OK, other than what I noted above. Since it is involved with the sending process, it doesn't seem to matter if you are using an existing template, create a new one, or copy a template first. It does seem to be totally around the step where you can choose to manually enter the phone number.

**Comment by anagradova** [comment]
I went to the QA template and reviewed the code. LGTM
