### ISSUE TITLE
Template for signing in/verifying email isn't using production URL

### ISSUE THREAD

**Issue by ccostino** [GSA/notifications-api#973]
The template that is used for the emails sent to users to sign back into Notify.gov (e.g., when needing to verify their email address after 90 days) is using the incorrect URL:

<img width="1121" alt="Screenshot 2024-05-07 at 5 13 05 PM" src="https://github.com/GSA/notifications-api/assets/121565/30910738-2ff1-46dd-bb1e-2eac8c50d310">

**Expected URL:**  `beta.notify.gov`
**Actual URL:**  `notify.app.cloud.gov`

While this will technically work, we should be using the user-facing production URL, not the cloud.gov provided one.

## Implementation Sketch and Acceptance Criteria

- [ ] Update the sign-in email template to reference the correct URL
- [ ] Make sure the template updates run in all environments; this should happen automatically now, but please verify!

## Security Considerations

- The public-facing URLs should be used instead of system default/system provided URLs.

**Comment by ecayer** [comment]
We believe this is done (checked with @ccostino ). Can't change production db to check, but we'll put the call out to make sure sure that this is done.

**Comment by ecayer** [comment]
Verified by @terrazoon. Closing.
